import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "@/utils/trpc";

export default function Home() {
  const hello = trpc.hello.useQuery({
    text: "hello 123",
  });
  const session = useSession();
  const product = trpc.product.get.useQuery(123);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navbar px-10">
        <div className="flex-1">
          <p className="text-lg">Logo</p>
        </div>
        <div className="flex-none">
          <ul className="menu-horizontal">
            {session.status === "authenticated" ? (
              <li className="my-auto mr-4">{session.data?.user?.name}</li>
            ) : (
              <li>
                <button
                  className="btn"
                  onClick={() => {
                    signIn("github");
                  }}
                >
                  login
                </button>
              </li>
            )}
          </ul>
        </div>
      </nav>
      <main className="container px-10">
        {hello.isLoading && <div>loading...</div>}
        <h1 className="text-5xl">{hello.data?.text}</h1>
        <button
          className="btn btn-primary mt-3"
          onClick={() => {
            hello.refetch();
          }}
        >
          refetch
        </button>
        {hello.error && <div>{hello.error.message}</div>}
      </main>
    </>
  );
}
